---
title: "Gov 50 Final Project"
author: "Kelly Olmos"
description: "My Final Project"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

Research Question: What is the relationship between a Republican candidate's stance on the 2020 election and their electoral success? In other words, consider how a Republican candidate's denial of the 2020 election results relates to their electoral success. 

For future: be more specific about the offices I'm refering to and word the research question better 

Formulate a hypothesis related to the research question. This hypothesis should be rooted in some sort of theory. In other words, you need to present a plausible story why the hypothesis might be true. Often, this is in the form of a behaviorial or institutional explanation. As social scientists, we are not interested in idiosyncratic explanations; we want to understand systematic patterns and relationships!

In Republican-leaning states, Republican candidates who deny the 2020 election results have greater electoral success and the opposite occurs in democratic-leaning states. 
[concede that this system is not perfect bc it is the aggregate of the state and we know that states can be politically fragmented with some urban centers being much more liberal than rural place maybe even use IL as an example]

Describe your explanatory variable(s) of interest and how it is measured. Importantly, we need to observe variation in this variable in order to study it!

The explanatory variable of interest is the Republican candidate's stance on the 2020 election results. It is a categorical variable measured 
"Candidates in the “Fully denied” category have explicitly said the 2020 election was illegitimate and/or took legal measures to try and overturn the election. Examples of the latter include members of Congress who voted against certifying election results or politicians who signed an amicus brief for a Texas lawsuit that challenged election results in four states President Biden won.
Candidates in the “Raised questions” category raised questions or concerns about the election but haven’t outright denied or affirmed it.
Candidates in the “Accepted with reservations” category have accepted Biden’s victory but have still raised questions or concerns about fraud.
Candidates in the “Fully accepted” category have accepted Biden’s victory without reservations.
Candidates in the “Avoided answering” category refused or avoided directly answering questions about the election (e.g., by changing the subject when asked about it).
Candidates in the “No comment” category have not made a public comment on the election (as far as we could tell) and did not respond to our inquiries on the topic." 
https://github.com/fivethirtyeight/data/tree/master/election-deniers

Describe your outcome variable of interest and how it is measured.
The outcome variable of interest is whether or not the Republican candidate won their race. 

What observed pattern in the data would provide support for your hypothesis? More importantly, what observed pattern would disprove your hypothesis?

[finish later]